# tools/cmake/definitions.cmake

if(WIN32)
    add_compile_definitions(MLW_WINDOWS)
elseif(UNIX AND NOT APPLE)
    add_compile_definitions(MLW_LINUX)
elseif(APPLE)
    add_compile_definitions(MLW_MAC)
else()
    message(WARNING "MLW: unknown platform")
endif()

if(CMAKE_BUILD_TYPE STREQUAL "Release")
    add_compile_definitions(MLW_RELEASE)
else()
    add_compile_definitions(MLW_DEBUG)
endif()

if(MSVC)
    add_compile_definitions(MLW_MSVC)
elseif(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
    add_compile_definitions(MLW_CLANG)
elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    add_compile_definitions(MLW_GCC)
else()
    message(WARNING "MLW: unknown compiler: ${CMAKE_CXX_COMPILER_ID}")
endif()


if(CMAKE_SYSTEM_PROCESSOR MATCHES "x86_64|AMD64")
    add_compile_definitions(MLW_X64)
elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "arm64|aarch64")
    add_compile_definitions(MLW_ARM64)
elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "arm")
    add_compile_definitions(MLW_ARM32)
elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "i386|i686|x86")
    add_compile_definitions(MLW_X86)
else()
    message(WARNING "MLW: unknown architecture: ${CMAKE_SYSTEM_PROCESSOR}")
endif()